server:
  port: 8101
spring:
  application:
    name: click-uz-config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://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@github.com/ismoil0709/click-uz-config-server-properties.git